server:
  # 端口号范围 0 ~ 65535
  # 公认端口：0 ~ 1023 。它们紧密绑定于一些服务，通常这些端口的通讯明确表明了某种服务的协议
  # 注册端口：1024 ~ 49151 。它们松散地绑定于一些服务，也就是说有许多服务绑定于这些端口
  # 动态和私有端口：49152 ~ 65535 。理论上，不应为服务分配这些端口
  port: 8080

### 基础配置
asa:
  base-package: pers.zj.asa
