### Spring 配置 ###
spring:
  ## 容器配置 ##
  application:
    name: asa-server

  ## 配置文件 ##
  profiles:
    active: local

  ## Servlet 配置 ##
  servlet:
    # 文件上传相关配置项
    multipart:
      # 单个文件大小
      max-file-size: 16MB
      # 设置总上传的文件大小
      max-request-size: 32MB

  ## Spring MVC 配置 ##
  mvc:
    # 出现错误时，直接抛出异常，方便统一处理
    throw-exception-if-no-handler-found: true
    # 静态资源路径
    # 注意：如果不配置，则 throw-exception-if-no-handler-found 不生效！
    # 该配置会导致 swagger 不生效！
    static-path-pattern: /static/**